numeros = set(range(1, 11))
print(numeros)
numeros.update([11, 12])
print(numeros)
numeros.update(range(30, 36))
print(numeros)
numeros.update([232, -264])
print(numeros)
primer_numero = min(numeros)
ultimo_numero = max(numeros)
print(primer_numero)
print(ultimo_numero)
print(7 in numeros)
print(20 in numeros)
print(len(numeros))